change version in CLA.Q while update githubrelease

diff --git a/.github/workflows/update_github_release.yml b/.github/workflows/update_github_release.yml
--- a/.github/workflows/update_github_release.yml
+++ b/.github/workflows/update_github_release.yml
@@ -29,6 +29,7 @@ jobs:
         echo "::endgroup::"
         
         sed -i "/version = /c{% set version = '$version_cutlang' %}" meta.yaml
+        sed -i "/cout << \"CLA v/c cout << \"CLA v$version_cutlang\\\t\";" ../../CLA/CLA.Q
         meta=`cat ../../scripts/conda/meta.yaml`
         echo "::group::META"
         echo "Inside group $meta"
@@ -54,7 +55,8 @@ jobs:
         git pull
 
         git add ./meta.yaml
-        git commit -m "automated update for scripts/conda meta.yaml" || echo "ignore commit failure, proceed (simple warning)"
+        git add ../../CLA/CLA.Q || echo "ignore commit failure, proceed (simple warning)"
+        git commit -m "automated update for CLA.Q scripts/conda meta.yaml" || echo "ignore commit failure, proceed (simple warning)"
         git push origin $1
 
     - name: Create a GitHub release
